name: Deploy GKE Cluster

on: workflow_dispatch

jobs:
  deploy_gke:
    name: Deploy GKE Cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.3'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: terraform Init
        run: |
          cd infrastructure
          terraform init
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Apply
        run: |
          cd infrastructure
          terraform apply -auto-approve
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
          GOOGLE_REGION: ${{ secrets.GCP_REGION }}

  deploy_podinfo:
    name: Deploy Podinfo Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: |
           echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
           gcloud auth activate-service-account --key-file=gcp-key.json

      # Get Kubernetes credentials
      - name: Get K8s Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }} --project ${{ secrets.GCP_PROJECT }}

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      # Apply Kustomize Configuration
      - name: Apply Kustomize Configuration
        run: kubectl apply -k application/
